### PR TITLE
Fixed `prediction_time` being read as a string

### PR DESCRIPTION
**Pull request by channemann**

### CODE REVIEW

**Comment by loudnate** [comment]
Can we do this in `__init__.py` instead?

**Comment by channemann** [comment]
Should, to make it universal and not converted on-the-fly.

**Comment by channemann** [comment]
Would that go in this block? https://github.com/channemann/openaps-predict/blob/wip-bg_momentum/openapscontrib/predict/__init__.py#L109-L114

**Comment by channemann** [comment]
Or here? https://github.com/channemann/openaps-predict/blob/wip-bg_momentum/openapscontrib/predict/__init__.py#L150

**Comment by loudnate** [comment]
The latter (line 150). Since the argparse type is Int, let's use `int()`
there too.

**Pull request merged**
